# Site wide configuration

title: Get Docker
description:  All realted to cloud technologies such as Docker, OpenStack and so on.
logo: 150x150.gif # 120x120 px default image used for Twitter summary card
teaser: 400x250.gif # 400x250 px default teaser image used in image archive grid
locale: en_US
url:

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Samuel Chen
  email: samuel@getdocker.com
  twitter: samuelchen
  google:
    ad-client: 
    ad-slot: 
  bio: An architect & develper
  avatar: bio-photo.jpg # 160x160 px image for author byline

# Disqus
disqus-shortname: getdocker


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
